### PR TITLE
feat: scroll selection into view

### LINKED ISSUE #90: Scroll selection into view
When dealing with large programs, I have problems finding the node for the selected expression resp. finding the expression for the selected node. It would be great if selecting a node/expression would reveal its counterpart in the other view!

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
✅ Closes: #90

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
https://user-images.githubusercontent.com/17974631/133374134-f99ffb48-b57b-4c4e-acd7-ec2f26c02bec.mp4

**Comment by IWANABETHATGUY** [comment]
@dsherret any idea on this pr?

**Review by dsherret — APPROVED** [review]
LGTM thanks @IWANABETHATGUY!

**Comment by dsherret** [comment]
> @dsherret any idea on this pr?

I don't have time to address PRs the same day always.

**Pull request merged**
